# Generated by Django 5.0.1 on 2024-02-04 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='slug',
        ),
    ]
